from pathlib import Path

import json

from poor_claude.launcher import ClaudeLaunchSpec, build_claude_command, prepare_launch_spec
from poor_claude.session import SessionRegistry


def test_build_claude_command_uses_local_settings_and_resume_id() -> None:
    command = build_claude_command(
        ClaudeLaunchSpec(
            session_id="demo",
            settings_path=Path("/tmp/settings.json"),
            mcp_config_path=Path("/tmp/mcp.json"),
            channel_name="poor-claude",
            workdir=Path("/tmp"),
            stdout_path=Path("/tmp/out.log"),
            stderr_path=Path("/tmp/err.log"),
        )
    )
    assert command == [
        "claude",
        "--session-id",
        "demo",
        "--settings",
        "/tmp/settings.json",
        "--dangerously-load-development-channels",
        "server:poor-claude",
    ]


def test_build_claude_command_can_skip_permissions_when_requested() -> None:
    command = build_claude_command(
        ClaudeLaunchSpec(
            session_id="demo",
            settings_path=Path("/tmp/settings.json"),
            mcp_config_path=Path("/tmp/mcp.json"),
            channel_name="poor-claude",
            workdir=Path("/tmp"),
            dangerously_skip_permissions=True,
        )
    )
    assert command[-1] == "--dangerously-skip-permissions"


def test_prepare_launch_spec_writes_merged_settings_and_metadata(tmp_path) -> None:
    base_settings = tmp_path / "base.json"
    base_settings.write_text(
        json.dumps({"hooks": {"PreToolUse": [{"hooks": [{"type": "command", "command": "broker"}]}]}}),
        encoding="utf-8",
    )
    registry = SessionRegistry()
    session = registry.create_or_get(
        session_id="demo",
        ttl_seconds=3600,
        keep_alive=False,
        workdir=str(tmp_path),
    )
    session.metadata["settings_path"] = str(base_settings)
    session.metadata["dangerously_skip_permissions"] = "True"

    spec = prepare_launch_spec(
        session=session,
        state_dir=tmp_path,
        callback_base_url="http://127.0.0.1:1234",
    )

    assert spec.session_id == "demo"
    assert spec.dangerously_skip_permissions is True
    assert session.metadata["merged_settings_path"] == str(spec.settings_path)
    assert session.metadata["mcp_config_path"] == str(tmp_path / ".mcp.json")
    assert session.metadata["mcp_log_path"].endswith("mcp-stdio.log")
    assert session.metadata["claude_stdout_path"].endswith("claude.stdout.log")
    assert session.metadata["claude_stderr_path"].endswith("claude.stderr.log")
    merged = json.loads(spec.settings_path.read_text(encoding="utf-8"))
    mcp_config = json.loads(spec.mcp_config_path.read_text(encoding="utf-8"))
    assert "PreToolUse" in merged["hooks"]
    assert "Stop" in merged["hooks"]
    assert "http://127.0.0.1:1234/hook/stop" in merged["hooks"]["Stop"][0]["hooks"][0]["command"]
    assert "poor-claude" in mcp_config["mcpServers"]
    env = mcp_config["mcpServers"]["poor-claude"]["env"]
    assert env["POOR_CLAUDE_CONTROL_URL"] == "http://127.0.0.1:1234"
    assert env["POOR_CLAUDE_ROUTE_KEY"] == session.route_key


def test_prepare_launch_spec_rejects_existing_foreign_project_mcp_servers(tmp_path) -> None:
    existing = tmp_path / ".mcp.json"
    existing.write_text(
        json.dumps({"mcpServers": {"other": {"command": "other"}}, "custom": True}),
        encoding="utf-8",
    )
    registry = SessionRegistry()
    session = registry.create_or_get(
        session_id="demo",
        ttl_seconds=3600,
        keep_alive=False,
        workdir=str(tmp_path),
    )

    try:
        prepare_launch_spec(
            session=session,
            state_dir=tmp_path / "state",
            callback_base_url="http://127.0.0.1:1234",
        )
    except ValueError as exc:
        assert "non-poor-claude MCP servers" in str(exc)
    else:  # pragma: no cover
        raise AssertionError("expected foreign MCP server rejection")


def test_prepare_launch_spec_rejects_existing_unowned_poor_claude_server(tmp_path) -> None:
    existing = tmp_path / ".mcp.json"
    existing.write_text(
        json.dumps({"mcpServers": {"poor-claude": {"command": "other"}}}),
        encoding="utf-8",
    )
    registry = SessionRegistry()
    session = registry.create_or_get(
        session_id="demo",
        ttl_seconds=3600,
        keep_alive=False,
        workdir=str(tmp_path),
    )

    try:
        prepare_launch_spec(
            session=session,
            state_dir=tmp_path / "state",
            callback_base_url="http://127.0.0.1:1234",
        )
    except ValueError as exc:
        assert "not generated by poor-claude" in str(exc)
    else:  # pragma: no cover
        raise AssertionError("expected unowned poor-claude server rejection")


def test_prepare_launch_spec_updates_existing_owned_poor_claude_server(tmp_path) -> None:
    existing = tmp_path / ".mcp.json"
    existing.write_text(
        json.dumps(
            {"mcpServers": {"poor-claude": {"command": "old", "env": {"POOR_CLAUDE_OWNED": "1"}}}}
        ),
        encoding="utf-8",
    )
    registry = SessionRegistry()
    session = registry.create_or_get(
        session_id="demo",
        ttl_seconds=3600,
        keep_alive=False,
        workdir=str(tmp_path),
    )

    prepare_launch_spec(
        session=session,
        state_dir=tmp_path / "state",
        callback_base_url="http://127.0.0.1:1234",
    )

    mcp_config = json.loads(existing.read_text(encoding="utf-8"))
    assert mcp_config["mcpServers"]["poor-claude"]["command"] != "old"
